=== StevenRD36/ExamenErikLoevbak/src/main/resources/XML/Movies.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="https://www.realdolmen.com/examen"
xmlns="https://www.realdolmen.com/examen"
elementFormDefault="qualified">
    <xs:element name="movies">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref = "movie" minOccurs = "1" maxOccurs ="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="movie" type ="movie"/>
   <xs:complexType name ="movie">
            <xs:sequence>
                <xs:element name = "id" type = "xs:string"/>
                <xs:element name = "title" type="xs:string"/>
                <xs:element name = "genre" type ="xs:string"/>
            </xs:sequence>
        </xs:complexType>
</xs:schema>

=== StevenRD36/ExamenErikLoevbak/src/main/resources/XML/Movies.xml
<?xml version="1.0" encoding="UTF-8"?>
<movies
xmlns="https://www.realdolmen.com/examen"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="https://www.realdolmen.com/examen Movies.xsd">
    <movie>
        <id>1</id>
        <title>The sixth sence</title>
        <genre>Thriller</genre>
    </movie>
    <movie>
        <id>2</id>
        <title>The seventh senSe</title>
        <genre>Thrillerer</genre>
    </movie>
    <movie>
        <id>69</id>
        <title>The steventh sense</title>
        <genre>The Thrillererest</genre>
    </movie>
</movies>
